name: Snyk

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      
      # Snyk does not work with setuptool files
      # Therefore need to convert it into requirements.txt
      - name: Prepare requirements for Snyk
        run: |
          python -m pip install .

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
